services:
  pgsql:
    image: postgres:17
    container_name: backend_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql_data:
